-- This file has been generated by Dungeon Editor 1.3.7

--- level 1 ---

mapName("Abyss of the Abject")
setWallSet("dungeon")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
######################...#######
######################...#######
######################...#######
######################...#######
######################...#######
#############...##..##....######
#############...##.......#######
###############..######.########
#########......#......#.########
#########.#.##...##.#.#.########
#########..#...#...#..#.########
##########.#.#.#.#.#.#..########
##########..#.....#..##....#####
###########.#.#.#.#.#...##.#.###
######....#..#...#..###......###
######.....#.#...###....##.#.###
######...#.#.#...#..###....#####
######...#.#..##.##.#.#.########
######...#..#...#........#######
##########...##...##.#.#########
##########.#..######.#.#########
#############..........#########
################.###############
###############..###############
###############..###############
################################
################################
################################
################################
################################
################################
################################
]])
spawn("torch_holder", 14,15,3, "torch_holder_2")
spawn("torch_holder", 15,16,2, "torch_holder_3")
spawn("torch_holder", 16,15,1, "torch_holder_4")
spawn("dungeon_secret_button_small", 16,16,1, "dungeon_secret_button_small_1")
	:addConnector("toggle", "dungeon_secret_door_1", "open")
spawn("dungeon_secret_door", 16,17,0, "dungeon_secret_door_1")
spawn("throwing_knife", 16,17,1, "throwing_knife_2")
spawn("throwing_knife", 16,17,1, "throwing_knife_3")
spawn("leather_gloves", 16,17,0, "leather_gloves_1")
spawn("dungeon_secret_door", 9,8,1, "dungeon_secret_door_2")
spawn("dungeon_secret_button_small", 11,9,1, "dungeon_secret_button_small_2")
	:addConnector("toggle", "dungeon_secret_door_2", "open")
spawn("torch_holder", 13,12,0, "torch_holder_1")
	:addTorch()
spawn("torch_holder", 17,12,0, "torch_holder_5")
	:addTorch()
spawn("torch_holder", 13,10,0, "torch_holder_6")
	:addTorch()
spawn("torch_holder", 17,10,0, "torch_holder_7")
	:addTorch()
spawn("torch_holder", 18,8,2, "torch_holder_8")
	:addTorch()
spawn("torch_holder", 12,8,2, "torch_holder_9")
	:addTorch()
spawn("torch_holder", 9,10,2, "torch_holder_10")
	:addTorch()
spawn("torch_holder", 11,12,1, "torch_holder_11")
	:addTorch()
spawn("torch_holder", 12,17,2, "torch_holder_12")
	:addTorch()
spawn("dungeon_secret_door", 19,17,0, "dungeon_secret_door_3")
spawn("dungeon_secret_button_small", 20,15,3, "dungeon_secret_button_small_3")
	:addConnector("toggle", "dungeon_secret_door_3", "open")
spawn("leather_boots", 18,16,3, "leather_boots_1")
spawn("leather_cap", 18,16,0, "leather_cap_1")
spawn("lock", 23,8,1, "lock_1")
	:setOpenedBy("iron_key")
	:addConnector("activate", "dungeon_door_metal_1", "open")
spawn("dungeon_door_metal", 23,7,2, "dungeon_door_metal_1")
spawn("iron_key", 18,14,3, "iron_key_1")
spawn("legionary_spear", 16,14,0, "legionary_spear_1")
spawn("leather_pants", 18,16,1, "leather_pants_1")
spawn("leather_pants", 16,17,2, "leather_pants_2")
spawn("peasant_tunic", 16,17,3, "peasant_tunic_1")
spawn("knife", 18,11,2, "knife_1")
spawn("tattered_cloak", 13,13,2, "tattered_cloak_1")
spawn("barrel_crate_block", 14,12,1, "barrel_crate_block_1")
spawn("sling", 15,14,1, "sling_1")
spawn("rock", 14,16,0, "rock_1")
spawn("rock", 14,16,3, "rock_2")
spawn("wooden_box", 21,21,0, "wooden_box_1")
	:addItem(spawn("scroll_fireburst"))	:addItem(spawn("scroll_ice_shards"))	:addItem(spawn("scroll_poison_cloud"))	:addItem(spawn("scroll_light"))	:addItem(spawn("scroll_shock"))spawn("barrel_crate_block", 19,21,1, "barrel_crate_block_2")
spawn("torch_holder", 16,19,0, "torch_holder_13")
	:addTorch()
spawn("torch_holder", 21,18,2, "torch_holder_14")
	:addTorch()
spawn("dungeon_secret_door", 26,14,1, "dungeon_secret_door_4")
spawn("torch_holder", 23,14,3, "torch_holder_15")
	:addTorch()
	:addConnector("any", "dungeon_secret_door_4", "open")
spawn("scavenger_swarm", 28,14,3, "scavenger_swarm_1")
spawn("scavenger_swarm", 28,15,3, "scavenger_swarm_2")
spawn("scavenger_swarm", 28,13,2, "scavenger_swarm_3")
spawn("herder_swarm", 27,14,3, "herder_swarm_1")
spawn("dungeon_secret_door", 18,21,3, "dungeon_secret_door_5")
	:setDoorState("open")
spawn("barrel_crate_block", 13,21,0, "barrel_crate_block_3")
spawn("torch_holder", 7,18,2, "torch_holder_16")
	:addTorch()
spawn("torch_holder", 7,14,0, "torch_holder_17")
	:addTorch()
spawn("long_sword", 6,18,0, "long_sword_1")
spawn("hand_axe", 8,18,0, "hand_axe_1")
spawn("dungeon_pit", 6,16,2, "dungeon_pit_1")
	:addTrapDoor()
	:setPitState("open")
spawn("dungeon_pit", 8,16,2, "dungeon_pit_2")
	:addTrapDoor()
	:setPitState("open")
spawn("barrel_crate_block", 6,14,2, "barrel_crate_block_7")
spawn("barrel_crate_block", 8,14,2, "barrel_crate_block_8")
spawn("dungeon_secret_door", 16,22,0, "dungeon_secret_door_6")
spawn("ring_boots", 15,23,0, "ring_boots_1")
spawn("ring_gauntlets", 15,23,3, "ring_gauntlets_1")
spawn("ring_greaves", 15,23,1, "ring_greaves_1")
spawn("ring_mail", 15,23,2, "ring_mail_1")
spawn("knoffer", 15,24,2, "knoffer_2")
spawn("dungeon_pressure_plate", 13,20,2, "dungeon_pressure_plate_1")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(true)
	:setActivateOnce(true)
	:addConnector("activate", "dungeon_secret_door_5", "toggle")
	:addConnector("activate", "dungeon_secret_door_6", "toggle")
	:addConnector("activate", "dungeon_secret_door_7", "open")
spawn("pitroot_bread", 15,24,3, "pitroot_bread_1")
spawn("pitroot_bread", 15,24,0, "pitroot_bread_2")
spawn("pitroot_bread", 15,24,1, "pitroot_bread_3")
spawn("lever", 6,18,2, "lever_1")
	:addConnector("any", "dungeon_secret_door_5", "toggle")
spawn("skeleton_archer_patrol", 8,17,0, "skeleton_archer_patrol_2")
spawn("skeleton_archer_patrol", 6,17,0, "skeleton_archer_patrol_1")
spawn("dungeon_stairs_down", 25,5,1, "dungeon_stairs_down_1")
spawn("dungeon_wall_text_long", 14,14,0, "dungeon_wall_text_long_1")
	:setWallText("May the damned herein absolve themselves through their eternal suffering and isolation.")
spawn("skeleton_archer_patrol", 7,17,0, "skeleton_archer_patrol_3")
spawn("crowern", 16,22,0, "crowern_1")
spawn("wyvern", 16,23,0, "wyvern_1")
spawn("dungeon_secret_door", 10,20,0, "dungeon_secret_door_7")
spawn("crowern", 10,20,0, "crowern_2")
spawn("rat_shank", 10,20,1, "rat_shank_1")
spawn("sandals", 10,20,3, "sandals_1")
spawn("peasant_cap", 10,20,2, "peasant_cap_1")
spawn("skeleton_patrol", 7,18,0, "skeleton_patrol_1")
spawn("dungeon_pit", 7,16,2, "dungeon_pit_3")
	:addTrapDoor()
	:setPitState("open")
spawn("dungeon_alcove", 14,14,3, "dungeon_alcove_1")
	:addItem(spawn("pitroot_bread"))
	:addItem(spawn("pitroot_bread"))
spawn("skeleton_patrol", 6,18,0, "skeleton_patrol_2")
spawn("skeleton_patrol", 8,18,0, "skeleton_patrol_3")
spawn("starting_location", 23,7,0, "starting_location_1")
spawn("dungeon_door_portcullis", 15,13,2, "dungeon_door_portcullis_1")
spawn("lever", 16,17,2, "lever_2")
	:addConnector("activate", "dungeon_door_portcullis_1", "open")
spawn("snail", 17,13,0, "snail_1")
spawn("snail", 18,11,0, "snail_2")
spawn("snail", 12,11,0, "snail_3")
spawn("crowern", 18,14,1, "crowern_3")
spawn("crowern", 20,12,0, "crowern_4")
spawn("skeleton_warrior", 16,7,3, "skeleton_warrior_1")
spawn("dungeon_secret_door", 16,7,2, "dungeon_secret_door_8")
spawn("dungeon_pressure_plate", 19,9,1, "dungeon_pressure_plate_2")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(true)
	:setTriggeredByItem(true)
	:addConnector("any", "dungeon_secret_door_8", "toggle")
	:addConnector("any", "dungeon_secret_door_9", "toggle")
	:addConnector("any", "dungeon_secret_door_10", "toggle")
	:addConnector("any", "dungeon_secret_door_11", "toggle")
spawn("dungeon_secret_door", 20,8,3, "dungeon_secret_door_9")
	:setDoorState("open")
spawn("lever", 19,14,2, "lever_3")
	:addConnector("any", "dungeon_secret_door_9", "toggle")
spawn("peasant_cap", 16,17,1, "peasant_cap_2")
spawn("tattered_cloak", 13,5,0, "tattered_cloak_4")
spawn("peasant_tunic", 13,5,3, "peasant_tunic_2")
spawn("peasant_cap", 13,5,1, "peasant_cap_3")
spawn("leather_boots", 13,5,2, "leather_boots_2")
spawn("leather_pants", 13,6,3, "leather_pants_3")
spawn("leather_gloves", 13,6,0, "leather_gloves_2")
spawn("leather_gloves", 17,13,1, "leather_gloves_3")
spawn("dungeon_secret_door", 16,9,3, "dungeon_secret_door_10")
	:setDoorState("open")
spawn("dungeon_secret_door", 14,8,2, "dungeon_secret_door_11")
spawn("secret", 16,17,0, "secret_1")
spawn("secret", 27,14,1, "secret_2")
spawn("skeleton_warrior", 19,16,2, "skeleton_warrior_2")
spawn("spider_eggs", 23,5,3, "spider_eggs_1")
spawn("spider_eggs", 24,6,0, "spider_eggs_2")
spawn("spider_eggs", 23,4,2, "spider_eggs_3")
spawn("spider_eggs", 24,4,3, "spider_eggs_4")
spawn("spider_eggs", 23,3,3, "spider_eggs_5")
spawn("spider_eggs", 24,3,1, "spider_eggs_6")
spawn("ogre", 24,5,3, "ogre_1")
spawn("spider_eggs", 22,4,2, "spider_eggs_7")
spawn("spider_eggs", 23,2,2, "spider_eggs_8")
spawn("spider_eggs", 24,2,2, "spider_eggs_9")
spawn("spider_eggs", 22,3,3, "spider_eggs_10")
spawn("spider_eggs", 22,2,2, "spider_eggs_11")
spawn("spider_eggs", 23,1,3, "spider_eggs_12")
spawn("spider_eggs", 24,0,3, "spider_eggs_13")
spawn("spider_eggs", 24,1,0, "spider_eggs_14")
spawn("dungeon_pressure_plate", 24,6,3, "dungeon_pressure_plate_3")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(true)
	:setTriggeredByItem(true)
	:setActivateOnce(true)
	:addConnector("activate", "dungeon_secret_door_12", "open")
spawn("dungeon_secret_door", 21,6,1, "dungeon_secret_door_12")
spawn("spider", 22,1,2, "spider_1")
spawn("spider", 23,0,1, "spider_2")

--- level 2 ---

mapName("Bowels of the Base")
setWallSet("dungeon")
playStream("assets/samples/music/dungeon_ambient.ogg")
mapDesc([[
################################
################################
################################
################################
################################
#########################...####
################################
################################
################################
################################
################################
################################
################################
################################
################################
######...#######################
#####.....######################
######...#######################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
################################
]])
spawn("dungeon_stairs_up", 25,5,3, "dungeon_stairs_up_1")
spawn("teleporter", 9,16,1, "teleporter_1")
	:setTriggeredByParty(true)
	:setTriggeredByMonster(false)
	:setTriggeredByItem(true)
	:setTeleportTarget(7,15,1,1)
	:setChangeFacing(false)
spawn("herder_big", 5,16,1, "herder_big_1")
spawn("herder_small", 7,17,0, "herder_small_1")
spawn("herder_small", 7,15,2, "herder_small_2")
spawn("tattered_cloak", 6,17,2, "tattered_cloak_2")
spawn("tattered_cloak", 6,17,2, "tattered_cloak_3")
spawn("dungeon_secret_button_large", 8,17,1, "dungeon_secret_button_large_1")
	:addConnector("toggle", "dungeon_pit_1", "toggle")
	:addConnector("toggle", "dungeon_pit_2", "toggle")
spawn("dungeon_secret_button_small", 5,16,3, "dungeon_secret_button_small_4")
	:addConnector("toggle", "dungeon_pit_3", "toggle")
